config/routes.rb
Registrar::Application.routes.draw do
  resources :invitations

  devise_for :users

  match 'authorize' => 'authorize#index'
  match 'authorize/callback' => 'authorize#callback'

  root :to => "invitations#new"

end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :inviter, :class_name => 'User'
  
  before_create :post_invite
  
  def post(url, params)
    inviter.access_token.post(url, params)
  end
  
  def cohuman_domain
    OAUTH_CREDENTIALS[:cohuman][:options][:site]
  end
  
  GENERAL_ERROR = "We are sorry. Something went wrong"
  
  def post_invite
    response = post("#{cohuman_domain}/invitation", :addresses => self.email, :format => 'json')
    if response.respond_to?(:body)
      hash = JSON.parse(response.body)
      invitee = hash['activity'] && hash['activity']['invitees'] && hash['activity']['invitees'].first
      invitee = hash['activity'] && hash['activity']['existing_users'] && hash['activity']['existing_users'].first unless invitee
      if invitee
        self.invitee_id = invitee['id'] 
        post_tasks
      else
        error = hash["error"] && hash["error"]["message"]
        raise error || GENERAL_ERROR
      end
    else
      raise GENERAL_ERROR
    end
  end
  
  def post_tasks
    response = post("#{cohuman_domain}/task", :owner_id => invitee_id, :format => 'json', :name => generate_names) rescue nil
  end
  
  def generate_names
    length = TASK_NAMES.size
    names = ""
    [rand(length), rand(length), rand(length)].each_with_index do |num, index|
      names << "#{TASK_NAMES[num]}"
      names << "; " unless index == 2
    end
    names
  end
  
  def get_tasks
    response = inviter.access_token.get("#{cohuman_domain}/user/#{invitee_id}", {"Content-Type" => "application/json"})
    array = []
    if response.respond_to?(:body)
      hash = JSON.parse(response.body)
      if task_array = hash['user'] && hash['user']['just_added_tasks']
        task_array.each do |task_hash|
          array << task_hash['name']
        end
      end
    end
    array
  end
  
  TASK_NAMES = [
    "Call my parents",
    "Do my taxes",
    "Plan a vacation",
    "Take out the trash",
    "Ask for a raise",
    "Ask for a new computer",
    "Update my resume",
    "Research raising chickens",
    "Start planning for Zombie apocalypse",
    "Fwd this to a Cohuman to become Pro 4 Free ",
    "Check out Cohuman API",
    "Create an app using Cohuman API",
    "Submit my SXSW expenses",
    "Pick a language to learn this year",
    "Hire an assistant",
    "Get passport photos shot",
    "Schedule office party",
    "Surprise Schnookums with a random gift",
    "Beat my boss to work next Tuesday",
    "Tidy up my desk",
    "Buy 'that guy' at work some deodorant",
    "Showoff Cohuman at the next company meeting",
    "Buy a new laptop bag",
    "Put money aside for iPhone5",
    "Remember Mother's day - May 8",
    "Tidy bedroom before date shows",
    "Cancel gym membership",
    "Re supply stockpile of twinkies & Doctor Pepper",
    "Test-test-test",
    "Buy another iPad... & a kindle",
    "Cancel gym membership",
    "Unsubscribe from mail order bride site",
    "Schedule doctor visit",
    "Find new dentist that has good breath",
    "Pay parking ticket",
    "Pay less taxes",
    "Update gravatar picture",
    "De-friend ex-girlfriend",
    "Change cell phone providers",
    "Repair bicycle",
    "Book travel to comic-con 7/21-24",
    "Remember Father's day June 19",
    "Friend Cohuman on Facebook",
    "Follow Cohuman on Twitter",
    "Subscribe to Cohuman Blog",
    "CLEAN TOILET -- before date",
    "Buy more TP and beer tonight",
    "Buy batteries for TV remote",
    "'Borrow' printer paper from work",
    "Buy a new toothbrush",
    "Record Game of Thrones premier April 17th 2011",
    "Schedule Poker night",
    "Get commitments from gang for college reunion",
    "Tell team I'm 'working from home' next Friday",
    "Buy lots of flowers",
    "Get a subscription to the New Yorker",
    "Tweet how awesome Cohuman is",
    "Replace office chair with one that doesn't smell",
    "Write my will"
  ].map(&:strip)
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  # GET /invitations
  # GET /invitations.xml
  before_filter :redirect_unless_token
  
  def index
    @invitations = Invitation.all(:conditions => {:inviter_id => current_user.id})

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @invitations }
    end
  end

  # GET /invitations/1
  # GET /invitations/1.xml
  def show
    @invitation = Invitation.find(params[:id])
    if @invitation.inviter_id != current_user.id
      redirect_to root_path 
    else
      @tasks = @invitation.get_tasks
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @invitation }
      end
    end
  end

  # GET /invitations/new
  # GET /invitations/new.xml
  def new
    @invitation = Invitation.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @invitation }
    end
  end

  # POST /invitations
  # POST /invitations.xml
  def create
    @invitation = Invitation.new(params[:invitation].merge(:inviter_id => current_user.id))

    begin
      @invitation.save
      redirect_to( @invitation, :notice => 'Invitation was successfully created.' )
    rescue Exception => e
      flash[:error] = e.message
      render :action => "new"
    end
  end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/_form.html.erb
<%= form_for(@invitation) do |f| %>
  <% if @invitation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invitation.errors.count, "error") %> prohibited this invitation from being saved:</h2>

      <ul>
      <% @invitation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit 'Invite!' %>
  </div>
<% end %>

app/views/invitations/index.html.erb
<h1>Listing invitations</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Inviter Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @invitations.each do |invitation| %>
  <tr>
    <td><%= invitation.email %></td>
    <td><%= invitation.inviter.email %></td>
    <td class='button show'><%= link_to 'Show', invitation, :class => 'button_link' %></td>
  </tr>
<% end %>
</table>

<br />

<div class='button'>
	<%= link_to 'New Invitation', new_invitation_path, :class => 'button_link' %>
</div>

app/views/invitations/new.html.erb
<%= render 'form' %>

app/views/invitations/show.html.erb
<p>
  <b>Email:</b>
  <%= @invitation.email %>
</p>

<p>
  <b>Inviter:</b>
  <%= @invitation.inviter.email %>
</p>
<hr>
<h4>Your Tasks:</h4>
<% @tasks.each do |task| -%>
	<p class='task'><%= task %></p>
<% end -%>
<div class='button'>		
	<%= link_to 'Invite More People', root_path, :class => 'button_link' %>
</div>